### ISSUE TITLE
actividad 5: realidad aumentada en sitio web

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-magaly#1]
[reporte de una aplicaion web_desarrollo de realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-magaly/files/14949129/reporte.de.una.aplicaion.web_desarrollo.de.realidad.aumentada.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
